### ISSUE TITLE
四卡4090跑5B模型VAE阶段显存爆了。

### ISSUE THREAD

**Issue by shifuxiao** [Wan-Video/Wan2.2#332]
我的启动命令是：root@9a01d14d6443:/workspace/Wan2.2# export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
root@9a01d14d6443:/workspace/Wan2.2# torchrun --nproc_per_node=4 generate.py --task ti2v-5B --size 1280*704 --ckpt_dir ./Wan2___2-TI2V-5B --dit_fsdp --t5_fsdp --ulysses_size 4 --image examples/i2v_input.JPG --prompt "Summer beach vacation style, a white cat wearing sunglasses sits on a surfboard. The fluffy-furred feline gazes directly at the camera with a relaxed expression. Blurred beach scenery forms the background featuring crystal-clear waters, distant green hills, and a blue sky dotted with white clouds. The cat assumes a naturally relaxed posture, as if savoring the sea breeze and warm sunlight. A close-up shot highlights the feline's intricate details and the refreshing atmosphere of the seaside."
最后vae阶段报显存了，请问我改怎么解决呢？我跑的是ti2v-5B 
[2026-02-05 05:42:33,516] INFO: Generation model config: {'__name__': 'Config: Wan TI2V 5B', 't5_model': 'umt5_xxl', 't5_dtype': torch.bfloat16, 'text_len': 512, 'param_dtype': torch.bfloat16, 'num_train_timesteps': 1000, 'sample_fps': 24, 'sample_neg_prompt': '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走', 'frame_num': 121, 't5_checkpoint': 'models_t5_umt5-xxl-enc-bf16.pth', 't5_tokenizer': 'google/umt5-xxl', 'vae_checkpoint': 'Wan2.2_VAE.pth', 'vae_stride': (4, 16, 16), 'patch_size': (1, 2, 2), 'dim': 3072, 'ffn_dim': 14336, 'freq_dim': 256, 'num_heads': 24, 'num_layers': 30, 'window_size': (-1, -1), 'qk_norm': True, 'cross_attn_norm': True, 'eps': 1e-06, 'sample_shift': 5.0, 'sample_steps': 50, 'sample_guide_scale': 5.0}
[2026-02-05 05:42:34,961] INFO: Input prompt: Summer beach vacation style, a white cat wearing sunglasses sits on a surfboard. The fluffy-furred feline gazes directly at the camera with a relaxed expression. Blurred beach scenery forms the background featuring crystal-clear waters, distant green hills, and a blue sky dotted with white clouds. The cat assumes a naturally relaxed posture, as if savoring the sea breeze and warm sunlight. A close-up shot highlights the feline's intricate details and the refreshing atmosphere of the seaside.
[2026-02-05 05:42:34,984] INFO: Input image: examples/i2v_input.JPG
[2026-02-05 05:42:34,984] INFO: Creating WanTI2V pipeline.
[2026-02-05 05:43:43,215] INFO: loading ./Wan2___2-TI2V-5B/models_t5_umt5-xxl-enc-bf16.pth
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 57.15it/s]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 58.98it/s]
[2026-02-05 05:43:56,663] INFO: loading ./Wan2___2-TI2V-5B/Wan2.2_VAE.pth
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 58.66it/s]
[2026-02-05 05:43:58,425] INFO: Creating WanModel from ./Wan2___2-TI2V-5B
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 59.42it/s]
[2026-02-05 05:44:06,418] INFO: Generating video ...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [05:35<00:00,  6.71s/it]

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [05:35<00:00,  6.71s/it]

[rank0]: Traceback (most recent call last):
[rank0]:   File "/workspace/Wan2.2/generate.py", line 575, in <module>
[rank0]:     generate(args)
[rank0]:   File "/workspace/Wan2.2/generate.py", line 443, in generate
[rank0]:     video = wan_ti2v.generate(
[rank0]:             ^^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/Wan2.2/wan/textimage2video.py", line 214, in generate
[rank0]:     return self.i2v(
[rank0]:            ^^^^^^^^^
[rank0]:   File "/workspace/Wan2.2/wan/textimage2video.py", line 609, in i2v
[rank0]:     videos = self.vae.decode(x0)
[rank0]:              ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/Wan2.2/wan/modules/vae2_2.py", line 1043, in decode
[rank0]:     return [
[rank0]:            ^
[rank0]:   File "/workspace/Wan2.2/wan/modules/vae2_2.py", line 1044, in <listcomp>
[rank0]:     self.model.decode(u.unsqueeze(0),
[rank0]:   File "/workspace/Wan2.2/wan/modules/vae2_2.py", line 831, in decode
[rank0]:     out_ = self.decoder(
[rank0]:            ^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/Wan2.2/wan/modules/vae2_2.py", line 700, in forward
[rank0]:     x = layer(x, feat_cache, feat_idx, first_chunk)
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/Wan2.2/wan/modules/vae2_2.py", line 492, in forward
[rank0]:     x_main = module(x_main, feat_cache, feat_idx)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/Wan2.2/wan/modules/vae2_2.py", line 215, in forward
[rank0]:     h = self.shortcut(x)
[rank0]:         ^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/Wan2.2/wan/modules/vae2_2.py", line 42, in forward
[rank0]:     return super().forward(x)
[rank0]:            ^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 725, in forward
[rank0]:     return self._conv_forward(input, self.weight, self.bias)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 720, in _conv_forward
[rank0]:     return F.conv3d(
[rank0]:            ^^^^^^^^^
[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.66 GiB. GPU 0 has a total capacity of 23.52 GiB of which 1.17 GiB is free. Process 1065429 has 22.33 GiB memory in use. Of the allocated memory 21.44 GiB is allocated by PyTorch, and 292.60 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[rank0]:[W205 05:49:49.734086030 ProcessGroupNCCL.cpp:1479] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
W0205 05:49:50.251000 3048 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 3114 closing signal SIGTERM
W0205 05:49:50.253000 3048 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 3115 closing signal SIGTERM
W0205 05:49:50.254000 3048 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 3116 closing signal SIGTERM
E0205 05:49:50.783000 3048 site-packages/torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: 1) local_rank: 0 (pid: 3113) of binary: /opt/conda/bin/python3.11
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/opt/conda/lib/python3.11/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/opt/conda/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 270, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
generate.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2026-02-05_05:49:50
  host      : 9a01d14d6443
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3113)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by Li-xt** [comment]
2 * 3090可以跑: https://github.com/Li-xt/Wan2.2

**Comment by WarmBring** [comment]
@Li-xt 请问replacement替换模型也可以正常运行吗

**Comment by xiading123** [comment]
> 2 * 3090可以跑: https://github.com/Li-xt/Wan2.2

请问主要做了哪些方面的优化呢？对结果有影响吗？

**Comment by xiading123** [comment]
> 2 * 3090可以跑: https://github.com/Li-xt/Wan2.2

以及优化是只针对于TI2V吗？其他I2V能通用吗？

**Comment by xiading123** [comment]
请问问题解决了吗？我现在也是持续爆显存中，同样是vae的decoder阶段
